#!/bin/bash

# Setup the client.
"$WERCKER_STEP_ROOT/mc" config host add "$WERCKER_MINIOSYNC_ALIAS" "$WERCKER_MINIOSYNC_URL" "$WERCKER_MINIOSYNC_ACCESS_KEY" "$WERCKER_MINIOSYNC_SECRET_KEY"

# Run the mirroring process.
if [ ! -n "$WERCKER_MINIOSYNC_FLAGS" ]; then
  export WERCKER_MINIOSYNC_FLAGS=--quiet
fi

"$WERCKER_STEP_ROOT/mc" cp "$WERCKER_MINIOSYNC_FLAGS" "$WERCKER_MINIOSYNC_SRC" "$WERCKER_MINIOSYNC_ALIAS/$WERCKER_MINIOSYNC_DST"
